version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./four_musketeers_restaurant
    volumes:
      # - "/home/ubuntu/four_musketeers_restaurant:/local"
      - "/Users/michaelweinberg/Desktop/school/coursework/tcss506/final/four_musketeers_restaurant"
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app    
  
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    depends_on:
      - flask_app  

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080